/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.categoria;

import controlador.CategoriaControlador;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CategoriaModelo;

/**
 *
 * @author Dell-UPN
 */
public class JInternalFrameCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameCategoria
     */
    public JInternalFrameCategoria() {
        initComponents();
        this.setSize(new Dimension(700, 500));
        this.setTitle("Producto");
        this.getContentPane().setBackground(Color.GRAY);

        listarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNombreCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCategoria = new javax.swing.JTable();
        textEstado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(textNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, 58));

        jLabel1.setText("Nombre Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 130, 50));

        TablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaCategoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 630, 150));
        getContentPane().add(textEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 280, 58));

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 130, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        CategoriaControlador controlador = new CategoriaControlador();
        CategoriaModelo cat = new CategoriaModelo();

        cat.setNombreCategoria(textNombreCategoria.getText());
        cat.setDescripcion(""); // Puedes reemplazar si tienes campo descripción
        cat.setEstado(Integer.parseInt(textEstado.getText()));

        int filaSeleccionada = TablaCategoria.getSelectedRow();
        String mensaje;

        if (filaSeleccionada == -1) {
            // ➕ CREAR NUEVA CATEGORÍA
            mensaje = controlador.crearCategoria(cat);
        } else {
            // ✏️ ACTUALIZAR CATEGORÍA SELECCIONADA
            int idCategoria = Integer.parseInt(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
            cat.setIdCategoria(idCategoria);
            mensaje = controlador.actualizarCategoria(cat);
        }

        JOptionPane.showMessageDialog(this, mensaje);
        controlador.cerrarConexion();
        listarCategorias();
        limpiarFormulario();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void limpiarFormulario() {
        textNombreCategoria.setText("");
        textEstado.setText("");
        TablaCategoria.clearSelection();
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = TablaCategoria.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una fila de la tabla.");
            return;
        }

        // Obtener el ID de la categoría desde la tabla
        int idCategoria = Integer.parseInt(modeloTabla.getValueAt(filaSeleccionada, 0).toString());

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar esta categoría?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            CategoriaControlador controlador = new CategoriaControlador();
            String mensaje = controlador.eliminarCategoria(idCategoria);
            controlador.cerrarConexion();
            JOptionPane.showMessageDialog(this, mensaje);
            listarCategorias(); // Refrescar tabla
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = TablaCategoria.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Debes seleccionar una fila de la tabla para editar.");
            return;
        }

        textNombreCategoria.setText(modeloTabla.getValueAt(fila, 1).toString());
        textEstado.setText(modeloTabla.getValueAt(fila, 2).toString());

    }//GEN-LAST:event_btnEditarActionPerformed

    private DefaultTableModel modeloTabla;

    private void listarCategorias() {

        modeloTabla = new DefaultTableModel(new String[]{"ID", "Nombre","Estado", "Descripción"}, 0);
        TablaCategoria.setModel(modeloTabla);

        modeloTabla.setRowCount(0); // Limpiar tabla

        CategoriaControlador controlador = new CategoriaControlador();
        List<CategoriaModelo> lista = controlador.listarCategorias();

        for (CategoriaModelo cat : lista) {
            modeloTabla.addRow(new Object[]{
                cat.getIdCategoria(),
                cat.getNombreCategoria(),
                cat.getEstado(),
                cat.getDescripcion()
            });
        }

        controlador.cerrarConexion();
    }

    // Listar categorías activas
//    private void listarCategorias() {
//        modeloTabla.setRowCount(0);
//        CategoriaControlador controlador = new CategoriaControlador();
//        List<CategoriaModelo> lista = controlador.listarCategorias();
//
//        for (CategoriaModelo cat : lista) {
//            modeloTabla.addRow(new Object[]{
//                cat.getIdCategoria(),
//                cat.getNombreCategoria(),
//                cat.getDescripcion()
//            });
//        }
//        controlador.cerrarConexion();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCategoria;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
