/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.herramientas;

import java.awt.Dimension;

/**
 *
 * @author Soporte
 */
public class JInternalFrameContador extends javax.swing.JInternalFrame {

    int numeroContador = 0;
    public JInternalFrameContador() {
        initComponents();
        
        this.setSize(new Dimension(400, 350));
        this.setTitle("Contador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contador = new javax.swing.JLabel();
        btnDisminuir = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contador.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("0");
        contador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, 90));

        btnDisminuir.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnDisminuir.setText("-");
        btnDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnAdicionar.setText("+");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirActionPerformed
        //Disminuir
        int resultado = numeroContador--;
        System.out.println(resultado);
        contador.setText(Integer.toString(resultado));
    }//GEN-LAST:event_btnDisminuirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int resultado = numeroContador++;
        System.out.println(resultado);
        contador.setText(Integer.toString(resultado));
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDisminuir;
    private javax.swing.JLabel contador;
    // End of variables declaration//GEN-END:variables
}
