/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.herramientas;

import java.awt.Color;
import java.awt.Dimension;

public class JInternalFrameContador extends javax.swing.JInternalFrame {

    int numeroContador;
    public JInternalFrameContador() {
        initComponents();
        
        this.setSize(new Dimension(400, 350));
        this.setTitle("Contador");
        this.getContentPane().setBackground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contador = new javax.swing.JLabel();
        btnDisminuir = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnMenos2 = new javax.swing.JButton();
        btnMas2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contador.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 255, 255));
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("0");
        contador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, 90));

        btnDisminuir.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnDisminuir.setText("-");
        btnDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnAdicionar.setText("+");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        btnMenos2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnMenos2.setText("-2");
        btnMenos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        btnMas2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnMas2.setText("+2");
        btnMas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMas2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirActionPerformed
        //Disminuir
        int resultado = numeroContador=numeroContador-1;
        contador.setText(Integer.toString(resultado));
    }//GEN-LAST:event_btnDisminuirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int resultado = numeroContador=numeroContador+1;
        contador.setText(Integer.toString(resultado));
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnMas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMas2ActionPerformed
        int resultado = numeroContador=numeroContador+2;
        contador.setText(Integer.toString(resultado));
    }//GEN-LAST:event_btnMas2ActionPerformed

    private void btnMenos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos2ActionPerformed
        int resultado = numeroContador=numeroContador-2;
        contador.setText(Integer.toString(resultado));
    }//GEN-LAST:event_btnMenos2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDisminuir;
    private javax.swing.JButton btnMas2;
    private javax.swing.JButton btnMenos2;
    private javax.swing.JLabel contador;
    // End of variables declaration//GEN-END:variables
}
